-- =============================================================================
-- MIGRACIÓN 20260619000000 — Tabla de notificaciones (No-op / Placeholder)
-- Fecha: 2026-06-19
-- Autor: Antigravity (Corrección)
--
-- Explicación:
-- Esta migración originalmente intentaba crear una tabla "notificaciones" y un enum
-- "tipo_notificacion_enum" con una estructura distinta (id_usuario_destino, leido, etc.).
-- Sin embargo, la tabla "notificaciones" y el tipo "tipo_notificacion_enum" ya existen
-- en la base de datos (creados en 20260608000001_initial_schema.sql) y son referenciados
-- activamente por todo el código de la aplicación (notification-actions.ts, NotificationBell.tsx,
-- edit-description.ts, strike-actions.ts, etc.) utilizando sus nombres de columnas originales
-- (id_usuario, tipo_evento, leida, generada_at).
--
-- Por lo tanto, para evitar colisiones y errores de migración (como el fallo en la creación de índices
-- sobre columnas que no existen), esta migración se mantiene como un no-op.
-- =============================================================================

-- (No se realizan cambios en el esquema aquí; el esquema original es el correcto y activo)
